spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.freemarker.suffix=.ftlh
spring.freemarker.content-type=text/html
spring.freemarker.charset=UTF-8
spring.freemarker.cache=false